cumulative_table <- rbind(ABCO_yr1 %>%
                            summarise(Species = "ABCO",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABCO_yr2 %>%
                            summarise(Species = "ABCO",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABCO_yr3 %>%
                            summarise(Species = "ABCO",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABCO_yr4 %>%
                            summarise(Species = "ABCO",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABCO_yr5 %>%
                            summarise(Species = "ABCO",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          ABGR_yr1 %>%
                            summarise(Species = "ABGR",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABGR_yr2 %>%
                            summarise(Species = "ABGR",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABGR_yr3 %>%
                            summarise(Species = "ABGR",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABGR_yr4 %>%
                            summarise(Species = "ABGR",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          ABGR_yr5 %>%
                            summarise(Species = "ABGR",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          CADE27_yr1 %>%
                            summarise(Species = "CADE27",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          CADE27_yr2 %>%
                            summarise(Species = "CADE27",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          CADE27_yr3 %>%
                            summarise(Species = "CADE27",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          CADE27_yr4 %>%
                            summarise(Species = "CADE27",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          CADE27_yr5 %>%
                            summarise(Species = "CADE27",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          LAOC_yr1 %>%
                            summarise(Species = "LAOC",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          LAOC_yr2 %>%
                            summarise(Species = "LAOC",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          LAOC_yr3 %>%
                            summarise(Species = "LAOC",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          LAOC_yr4 %>%
                            summarise(Species = "LAOC",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          LAOC_yr5 %>%
                            summarise(Species = "LAOC",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          PICO_yr1 %>%
                            summarise(Species = "PICO",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PICO_yr2 %>%
                            summarise(Species = "PICO",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PICO_yr3 %>%
                            summarise(Species = "PICO",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PICO_yr4 %>%
                            summarise(Species = "PICO",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PICO_yr5 %>%
                            summarise(Species = "PICO",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          PILA_yr1 %>%
                            summarise(Species = "PILA",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PILA_yr2 %>%
                            summarise(Species = "PILA",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PILA_yr3 %>%
                            summarise(Species = "PILA",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PILA_yr4 %>%
                            summarise(Species = "PILA",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PILA_yr5 %>%
                            summarise(Species = "PILA",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          PIPO_yr1 %>%
                            summarise(Species = "PIPO",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PIPO_yr2 %>%
                            summarise(Species = "PIPO",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PIPO_yr3 %>%
                            summarise(Species = "PIPO",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PIPO_yr4 %>%
                            summarise(Species = "PIPO",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PIPO_yr5 %>%
                            summarise(Species = "PIPO",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          PSME_yr1 %>%
                            summarise(Species = "PSME",
                                      PostFire_Yr = 1,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PSME_yr2 %>%
                            summarise(Species = "PSME",
                                      PostFire_Yr = 2,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PSME_yr3 %>%
                            summarise(Species = "PSME",
                                      PostFire_Yr = 3,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PSME_yr4 %>%
                            summarise(Species = "PSME",
                                      PostFire_Yr = 4,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')),
                          
                          PSME_yr5 %>%
                            summarise(Species = "PSME",
                                      PostFire_Yr = 5,
                                      live=length(Status) - sum(Status),
                                      dead=sum(Status),
                                      Mortality = dead/length(Status) * 100,
                                      meanCVS = mean(CVS_percent),
                                      medianCVS = median(CVS_percent),
                                      meanBCH = mean(BCH_percent),
                                      medianBCH = median(BCH_percent),
                                      meanDBH = mean(DBH_cm),
                                      medianDBH = median(DBH_cm),
                                      MinMax = paste(min(DBH_cm), max(DBH_cm), sep='/')))
                          
                        





write.csv(cumulative_table, file="cumulative_table.csv")

